name: tic_tac_toe
description: A Tic Tac Toe game built with Flutter.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  clipboard: ^0.1.3
  cloud_firestore: ^5.0.1
  concentric_transition: ^1.0.3
  confetti: ^0.7.0
  dotted_border: ^2.1.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  get: ^4.6.6
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
